// Launch catalog: exactly 100 curated business apps.
// "native" means a typed AgentForge action. "universal" means the app works
// through AgentForge's authenticated HTTP action or signed webhook trigger.
const APPS = [
  ['slack','Slack','Communication','native'],
  ['google_sheets','Google Sheets','Productivity','native'],
  ['google_drive','Google Drive','Storage','native'],
  ['resend','Resend','Email','native'],
  ['supabase','Supabase','Database','native'],
  ['github','GitHub','Engineering','native'],
  ['discord','Discord','Communication','native'],
  ['notion','Notion','Productivity','native'],
  ['airtable','Airtable','Database','native'],
  ['hubspot','HubSpot','CRM','native'],
  ['salesforce','Salesforce','CRM','native'],
  ['stripe','Stripe','Commerce','native'],
  ['shopify','Shopify','Commerce','native'],
  ['jira','Jira','Engineering','native'],
  ['linear','Linear','Engineering','native'],
  ['twilio','Twilio','Communication','native'],
  ['zendesk','Zendesk','Support','native'],
  ['microsoft_teams','Microsoft Teams','Communication','native'],
  ['gmail','Gmail','Email','native'],
  ['microsoft_outlook','Microsoft Outlook','Email','native'],
  ['google_calendar','Google Calendar','Productivity','native'],
  ['telegram','Telegram','Communication','universal'],
  ['whatsapp_business','WhatsApp Business','Communication','universal'],
  ['zoom','Zoom','Communication','native'],
  ['calendly','Calendly','Scheduling','native'],
  ['asana','Asana','Project management','native'],
  ['trello','Trello','Project management','native'],
  ['monday','monday.com','Project management','universal'],
  ['clickup','ClickUp','Project management','universal'],
  ['todoist','Todoist','Productivity','universal'],
  ['dropbox','Dropbox','Storage','universal'],
  ['box','Box','Storage','universal'],
  ['onedrive','OneDrive','Storage','universal'],
  ['confluence','Confluence','Productivity','universal'],
  ['figma','Figma','Design','universal'],
  ['canva','Canva','Design','universal'],
  ['miro','Miro','Design','universal'],
  ['pipedrive','Pipedrive','CRM','universal'],
  ['zoho_crm','Zoho CRM','CRM','universal'],
  ['dynamics_365','Microsoft Dynamics 365','CRM','universal'],
  ['intercom','Intercom','Support','universal'],
  ['freshdesk','Freshdesk','Support','universal'],
  ['servicenow','ServiceNow','IT operations','universal'],
  ['mailchimp','Mailchimp','Marketing','universal'],
  ['activecampaign','ActiveCampaign','Marketing','universal'],
  ['brevo','Brevo','Marketing','universal'],
  ['sendgrid','SendGrid','Email','universal'],
  ['klaviyo','Klaviyo','Marketing','universal'],
  ['customer_io','Customer.io','Marketing','universal'],
  ['typeform','Typeform','Forms','universal'],
  ['jotform','Jotform','Forms','universal'],
  ['surveymonkey','SurveyMonkey','Forms','universal'],
  ['facebook_pages','Facebook Pages','Social','universal'],
  ['instagram_business','Instagram for Business','Social','universal'],
  ['linkedin','LinkedIn','Social','universal'],
  ['youtube','YouTube','Media','universal'],
  ['wordpress','WordPress','Content','universal'],
  ['paypal','PayPal','Commerce','universal'],
  ['square','Square','Commerce','universal'],
  ['woocommerce','WooCommerce','Commerce','universal'],
  ['bigcommerce','BigCommerce','Commerce','universal'],
  ['quickbooks','QuickBooks','Finance','universal'],
  ['xero','Xero','Finance','universal'],
  ['chargebee','Chargebee','Finance','universal'],
  ['razorpay','Razorpay','Finance','universal'],
  ['adyen','Adyen','Finance','universal'],
  ['plaid','Plaid','Finance','universal'],
  ['postgresql','PostgreSQL','Database','universal'],
  ['mysql','MySQL','Database','universal'],
  ['mongodb','MongoDB','Database','universal'],
  ['snowflake','Snowflake','Data','universal'],
  ['bigquery','Google BigQuery','Data','universal'],
  ['datadog','Datadog','Observability','universal'],
  ['sentry','Sentry','Observability','universal'],
  ['gitlab','GitLab','Engineering','universal'],
  ['bitbucket','Bitbucket','Engineering','universal'],
  ['circleci','CircleCI','Engineering','universal'],
  ['vercel','Vercel','Cloud','universal'],
  ['netlify','Netlify','Cloud','universal'],
  ['cloudflare','Cloudflare','Cloud','universal'],
  ['aws','Amazon Web Services','Cloud','universal'],
  ['azure','Microsoft Azure','Cloud','universal'],
  ['google_cloud','Google Cloud','Cloud','universal'],
  ['docker_hub','Docker Hub','Engineering','universal'],
  ['pagerduty','PagerDuty','IT operations','universal'],
  ['grafana','Grafana','Observability','universal'],
  ['elasticsearch','Elasticsearch','Data','universal'],
  ['openai','OpenAI','AI','universal'],
  ['anthropic','Anthropic','AI','universal'],
  ['google_gemini','Google Gemini','AI','universal'],
  ['perplexity','Perplexity','AI','universal'],
  ['pinecone','Pinecone','AI','universal'],
  ['weaviate','Weaviate','AI','universal'],
  ['qdrant','Qdrant','AI','universal'],
  ['docusign','DocuSign','Documents','universal'],
  ['adobe_sign','Adobe Acrobat Sign','Documents','universal'],
  ['loom','Loom','Media','universal'],
  ['gong','Gong','Sales','universal'],
  ['apollo_io','Apollo.io','Sales','universal'],
  ['segment','Twilio Segment','Data','universal'],
]

export const INTEGRATION_CATALOG = Object.freeze(APPS.map(([slug, name, category, mode]) => Object.freeze({
  id:slug,
  slug,
  name,
  category,
  mode,
  status:mode === 'native' ? 'Native connector' : 'Universal connector',
  setupGuide:mode === 'native'
    ? ['Add a least-privilege credential or consent connection', 'Run the connection test', 'Insert the typed action in Build', 'Test with sample data before activation']
    : ['Create a least-privilege API credential', 'Choose the documented API endpoint or signed webhook', 'Run a sample request in Build', 'Keep external delivery behind approval until verified'],
  sampleOperation:mode === 'native' ? `Test a typed ${name} action` : `Test an authenticated ${name} API request`,
  errorHelp:'Open Activity for the provider response, verify credential scope, then retry the failed node.',
  workflowPath:'/workflows/new',
})))

export const INTEGRATION_CATEGORIES = Object.freeze([
  'All', ...new Set(INTEGRATION_CATALOG.map(app => app.category).sort()),
])

export const INTEGRATION_COUNTS = Object.freeze({
  catalog:INTEGRATION_CATALOG.length,
  native:INTEGRATION_CATALOG.filter(app => app.mode === 'native').length,
  universal:INTEGRATION_CATALOG.filter(app => app.mode === 'universal').length,
})
